version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/raf924/connector-api
    versions:
    - 1.0.0-alpha.4
    - 1.0.0-alpha.6
  - dependency-name: github.com/raf924/bot
    versions:
    - 1.0.0-alpha.14
    - 1.0.0-alpha.15
    - 1.0.0-alpha.21
  - dependency-name: github.com/google/uuid
    versions:
    - 1.2.0
  - dependency-name: google.golang.org/grpc
    versions:
    - 1.35.0
    - 1.36.0
    - 1.36.1
  - dependency-name: github.com/golang/protobuf
    versions:
    - 1.5.1
  - dependency-name: google.golang.org/protobuf
    versions:
    - 1.26.0
